name: Update Dependencies

on:
  schedule:
    # Run every Sunday at 6 AM UTC
    - cron: "0 6 * * 0"
  workflow_dispatch: # Allow manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install npm-check-updates
        run: npm install -g npm-check-updates

      - name: Update dependencies
        run: |
          ncu -u
          npm install

      - name: Run tests
        run: npm run test:run

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "chore: automated dependency updates"
          body: |
            Automated dependency update created by GitHub Actions.

            - Updated package.json with latest compatible versions
            - All tests passing ✅

            Please review the changes before merging.
          branch: automated-dependency-updates
          delete-branch: true
